[package]
name = "wordcount"
version = "0.1.0"
authors = ["letitride <ichikawa.fumiya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
